package model;
// Generated 15-Oct-2019 18:01:41 by Hibernate Tools 4.3.1



/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private Integer credito;
     private Integer cargaHoraria;
     private String regente;
     private String assistente;

    public Disciplina() {
    }

	
    public Disciplina(String nome) {
        this.nome = nome;
    }
    public Disciplina(String nome, Integer credito, Integer cargaHoraria, String regente, String assistente) {
       this.nome = nome;
       this.credito = credito;
       this.cargaHoraria = cargaHoraria;
       this.regente = regente;
       this.assistente = assistente;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getCredito() {
        return this.credito;
    }
    
    public void setCredito(Integer credito) {
        this.credito = credito;
    }
    public Integer getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(Integer cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public String getRegente() {
        return this.regente;
    }
    
    public void setRegente(String regente) {
        this.regente = regente;
    }
    public String getAssistente() {
        return this.assistente;
    }
    
    public void setAssistente(String assistente) {
        this.assistente = assistente;
    }




}


