package model;
// Generated 29-Sep-2019 16:34:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;


/**
 * Disciplina generated by hbm2java
 */

public class Disciplina  implements java.io.Serializable {


     private Integer codigo;
     
     private Docente docente;
     private String nome;
     private Integer credito;
     private Integer cargaHoraria;
     private String regente;
     private String assistente;
     private Set docentedisciplinas = new HashSet(0);

    public Disciplina() {
    }


    public Disciplina(Docente docente, String nome) {
        this.docente = docente;
        this.nome = nome;
    }
    public Disciplina(Docente docente, String nome, Integer credito, Integer cargaHoraria, String regente, String assistente, Set docentedisciplinas) {
       this.docente = docente;
       this.nome = nome;
       this.credito = credito;
       this.cargaHoraria = cargaHoraria;
       this.regente = regente;
       this.assistente = assistente;
       this.docentedisciplinas = docentedisciplinas;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getCredito() {
        return this.credito;
    }
    
    public void setCredito(Integer credito) {
        this.credito = credito;
    }
    public Integer getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(Integer cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public String getRegente() {
        return this.regente;
    }
    
    public void setRegente(String regente) {
        this.regente = regente;
    }
    public String getAssistente() {
        return this.assistente;
    }
    
    public void setAssistente(String assistente) {
        this.assistente = assistente;
    }
    public Set getDocentedisciplinas() {
        return this.docentedisciplinas;
    }
    
    public void setDocentedisciplinas(Set docentedisciplinas) {
        this.docentedisciplinas = docentedisciplinas;
    }




}


