package model;
// Generated 29-Sep-2019 16:34:04 by Hibernate Tools 4.3.1



/**
 * Docentedisciplina generated by hbm2java
 */
public class Docentedisciplina  implements java.io.Serializable {


     private int id;
     private Disciplina disciplina;
     private Docente docente;

    public Docentedisciplina() {
    }

	
    public Docentedisciplina(int id) {
        this.id = id;
    }
    public Docentedisciplina(int id, Disciplina disciplina, Docente docente) {
       this.id = id;
       this.disciplina = disciplina;
       this.docente = docente;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }




}


