package model;
// Generated 29-Sep-2019 16:34:04 by Hibernate Tools 4.3.1



/**
 * Docenteturma generated by hbm2java
 */
public class Docenteturma  implements java.io.Serializable {


     private int id;
     private Docente docente;
     private Turma turma;

    public Docenteturma() {
    }

	
    public Docenteturma(int id) {
        this.id = id;
    }
    public Docenteturma(int id, Docente docente, Turma turma) {
       this.id = id;
       this.docente = docente;
       this.turma = turma;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Turma getTurma() {
        return this.turma;
    }
    
    public void setTurma(Turma turma) {
        this.turma = turma;
    }




}


