package model;
// Generated 29-Sep-2019 16:34:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private Integer codigo;
     private Utilizador utilizador;
     private String nome;
     private String categoria;
     private Set docentedisciplinas = new HashSet(0);
     private Set docenteturmas = new HashSet(0);
     private Disciplina disciplina;

    public Docente() {
    }

	
    public Docente(String nome) {
        this.nome = nome;
    }
    public Docente(Utilizador utilizador, String nome, String categoria, Set docentedisciplinas, Set docenteturmas, Disciplina disciplina) {
       this.utilizador = utilizador;
       this.nome = nome;
       this.categoria = categoria;
       this.docentedisciplinas = docentedisciplinas;
       this.docenteturmas = docenteturmas;
       this.disciplina = disciplina;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Utilizador getUtilizador() {
        return this.utilizador;
    }
    
    public void setUtilizador(Utilizador utilizador) {
        this.utilizador = utilizador;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Set getDocentedisciplinas() {
        return this.docentedisciplinas;
    }
    
    public void setDocentedisciplinas(Set docentedisciplinas) {
        this.docentedisciplinas = docentedisciplinas;
    }
    public Set getDocenteturmas() {
        return this.docenteturmas;
    }
    
    public void setDocenteturmas(Set docenteturmas) {
        this.docenteturmas = docenteturmas;
    }
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }




}


