package model;
// Generated Oct 2, 2019 4:04:30 PM by Hibernate Tools 4.3.1



/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private String categoria;
     private String email;
     private String senha;

    public Docente() {
    }

	
    public Docente(String nome) {
        this.nome = nome;
    }
    public Docente(String nome, String categoria, String email, String senha) {
       this.nome = nome;
       this.categoria = categoria;
       this.email = email;
       this.senha = senha;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


