package model;
// Generated Oct 2, 2019 4:04:30 PM by Hibernate Tools 4.3.1



/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {


     private Integer codigo;
     private String curso;
     private String tutor;
     private Integer nivel;
     private String email;
     private String senha;

    public Turma() {
    }

	
    public Turma(String curso) {
        this.curso = curso;
    }
    public Turma(String curso, String tutor, Integer nivel, String email, String senha) {
       this.curso = curso;
       this.tutor = tutor;
       this.nivel = nivel;
       this.email = email;
       this.senha = senha;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getTutor() {
        return this.tutor;
    }
    
    public void setTutor(String tutor) {
        this.tutor = tutor;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


