package model;
// Generated 06-Oct-2019 16:27:09 by Hibernate Tools 4.3.1



/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {


     private Integer codigo;
     private String curso;
     private String tutor;
     private String regime;
     private Integer nivel;
     private String email;

    public Turma() {
    }

	
    public Turma(String curso) {
        this.curso = curso;
    }
    public Turma(String curso, String tutor, String regime, Integer nivel, String email) {
       this.curso = curso;
       this.tutor = tutor;
       this.regime = regime;
       this.nivel = nivel;
       this.email = email;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getTutor() {
        return this.tutor;
    }
    
    public void setTutor(String tutor) {
        this.tutor = tutor;
    }
    public String getRegime() {
        return this.regime;
    }
    
    public void setRegime(String regime) {
        this.regime = regime;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


