package model;
// Generated 29-Sep-2019 16:34:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Utilizador generated by hbm2java
 */
public class Utilizador  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private String entidade;
     private String senha;
     private String email;
     private Set docentes = new HashSet(0);
     private Set turmas = new HashSet(0);

    public Utilizador() {
    }

    public Utilizador(String nome, String entidade, String senha, String email, Set docentes, Set turmas) {
       this.nome = nome;
       this.entidade = entidade;
       this.senha = senha;
       this.email = email;
       this.docentes = docentes;
       this.turmas = turmas;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEntidade() {
        return this.entidade;
    }
    
    public void setEntidade(String entidade) {
        this.entidade = entidade;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }




}


