package model;
// Generated 15-Oct-2019 18:01:41 by Hibernate Tools 4.3.1



/**
 * Utilizador generated by hbm2java
 */
public class Utilizador  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private String entidade;
     private String senha;
     private String email;

    public Utilizador() {
    }

    public Utilizador(String nome, String entidade, String senha, String email) {
       this.nome = nome;
       this.entidade = entidade;
       this.senha = senha;
       this.email = email;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEntidade() {
        return this.entidade;
    }
    
    public void setEntidade(String entidade) {
        this.entidade = entidade;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


