package hiber.entity;
// Generated 23-Sep-2019 17:50:31 by Hibernate Tools 4.3.1



/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private Integer codigoDisciplina;
     private String nomeDisciplina;
     private Integer credito;
     private Integer cargaHoraria;

    public Disciplina() {
    }

	
    public Disciplina(String nomeDisciplina) {
        this.nomeDisciplina = nomeDisciplina;
    }
    public Disciplina(String nomeDisciplina, Integer credito, Integer cargaHoraria) {
       this.nomeDisciplina = nomeDisciplina;
       this.credito = credito;
       this.cargaHoraria = cargaHoraria;
    }
   
    public Integer getCodigoDisciplina() {
        return this.codigoDisciplina;
    }
    
    public void setCodigoDisciplina(Integer codigoDisciplina) {
        this.codigoDisciplina = codigoDisciplina;
    }
    public String getNomeDisciplina() {
        return this.nomeDisciplina;
    }
    
    public void setNomeDisciplina(String nomeDisciplina) {
        this.nomeDisciplina = nomeDisciplina;
    }
    public Integer getCredito() {
        return this.credito;
    }
    
    public void setCredito(Integer credito) {
        this.credito = credito;
    }
    public Integer getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(Integer cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }




}


