package hiber.entity;
// Generated 23-Sep-2019 17:50:31 by Hibernate Tools 4.3.1



/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private Integer codigo;
     private String nomeDocente;
     private String categoria;
     private String nivel;

    public Docente() {
    }

	
    public Docente(String nomeDocente) {
        this.nomeDocente = nomeDocente;
    }
    public Docente(String nomeDocente, String categoria, String nivel) {
       this.nomeDocente = nomeDocente;
       this.categoria = categoria;
       this.nivel = nivel;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNomeDocente() {
        return this.nomeDocente;
    }
    
    public void setNomeDocente(String nomeDocente) {
        this.nomeDocente = nomeDocente;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }




}


