package hiber.entity;
// Generated 27-Sep-2019 19:25:48 by Hibernate Tools 4.3.1



/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer codigo;
     private Turma turma;
     private String semestre;
     private Integer ano;

    public Horario() {
    }

	
    public Horario(Turma turma, String semestre) {
        this.turma = turma;
        this.semestre = semestre;
    }
    public Horario(Turma turma, String semestre, Integer ano) {
       this.turma = turma;
       this.semestre = semestre;
       this.ano = ano;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Turma getTurma() {
        return this.turma;
    }
    
    public void setTurma(Turma turma) {
        this.turma = turma;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }




}


