package hiber.entity;
// Generated 23-Sep-2019 17:50:31 by Hibernate Tools 4.3.1



/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {


     private Integer codigo;
     private String nomeTurma;
     private Integer nivel;
     private String tutor;

    public Turma() {
    }

	
    public Turma(String nomeTurma) {
        this.nomeTurma = nomeTurma;
    }
    public Turma(String nomeTurma, Integer nivel, String tutor) {
       this.nomeTurma = nomeTurma;
       this.nivel = nivel;
       this.tutor = tutor;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNomeTurma() {
        return this.nomeTurma;
    }
    
    public void setNomeTurma(String nomeTurma) {
        this.nomeTurma = nomeTurma;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public String getTutor() {
        return this.tutor;
    }
    
    public void setTutor(String tutor) {
        this.tutor = tutor;
    }




}


