package hiber.entity;
// Generated 27-Sep-2019 19:25:48 by Hibernate Tools 4.3.1



/**
 * Utilizador generated by hbm2java
 */
public class Utilizador  implements java.io.Serializable {


     private Integer codigo;
     private String nomeUser;
     private String entidade;
     private String senha;
  

    public Utilizador() {
    }

    public Utilizador(String nomeUser, String entidade, String senha) {
       this.nomeUser = nomeUser;
       this.entidade = entidade;
       this.senha = senha;
   
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNomeUser() {
        return this.nomeUser;
    }
    
    public void setNomeUser(String nomeUser) {
        this.nomeUser = nomeUser;
    }
    public String getEntidade() {
        return this.entidade;
    }
    
    public void setEntidade(String entidade) {
        this.entidade = entidade;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }





}


